### PR TITLE
Reduced dependence on snippets

### PR DESCRIPTION
**Pull request by cshold**
Here is an experimental PR that places all code from one-use snippets in line.

*Pros of this approach:*
- Reduced noise in `/snippets`
- Easier for merchants to find elements per template
  - Prime example was to find the `{{ powered_by_link }}`. Timber used to have it in `snippets/footer`, rather than `layouts/theme` - the only place it is ever used

*Cons:*
- Makes template/layout files much longer and harder to traverse (at times)

My preference would be to take any snippet that is only used once and move it inline. Exceptions would be:
- Open graph meta tags
- Twitter card meta tags
- Old IE shivs/polyfills
- Handlebar.js ajax cart templates
- Onboarding markup?
  - These are used once, but will never be to be edited by a merchant

These make the main layout file much longer than it needs to be, as seen in this PR. These are never going to be touched by a merchant and therefor offer no value in the main layout file.

@mpiotrowicz @carolineschnapp @fredryk @stevebosworth

### CODE REVIEW

**Comment by carolineschnapp** [comment]
I am in total agreement with the general rule proposed here, and the listed of exceptions provided.

**Comment by carolineschnapp** [comment]
_Eventually_ we could make a case that `{{ content_for_header }}` already contain Open graph tags and Twitter rich snippets, since the likelihood of a merchant editing those files is very low.

**Comment by fredryk** [comment]
Ten snippets lighter! I'm all for this, and the list of exceptions.

**Comment by carolineschnapp** [comment]
Another situation where snippets are needed now is when you have theme settings that let you populate a sidebar or a homepage with “widgets” **in the order that you want**. 

Like we do in the Solo theme. Perhaps there's another way to handle that fine-grained control that we obtain with snippets then.

Solo's index template contains this:

    {% if settings.home_section_1 != blank %}
      {% include settings.home_section_1 %}
    {% endif %}

**Comment by cshold** [comment]
I think that's another conversation to be had for sure, but not handled in this PR. Right now it's the best solution I can think of to handle the ordering of settings like that.

**Comment by carolineschnapp** [comment]
Sorry, not the right place for sure.

**Comment by cshold** [comment]
Using #361 for this now.

**Pull request closed without merging**
