### PR TITLE
v2.1.1 Doc updates

### PR DESCRIPTION
**Pull request by cshold**
Updated `at-query` mixin docs to go with #367

### CODE REVIEW

**Comment by cshold** [comment]
@haeky Hey, any chance you can disable tests for anything merging into `gh-pages`? It's our docs page and doesn't act like a theme at all.

**Comment by haeky** [comment]
Sure can!

**Comment by haeky** [comment]
This one won't probably go away but it should for the next ones.

**Comment by jtgrenz** [comment]
Doc update looks good to me.

**Pull request merged**
