### PR TITLE
Updated icon set

### PR DESCRIPTION
**Pull request by cshold**
#### New payment icons
- Dogecoin
- Dwolla
- Forbrugsforeningen
- Laser
- Litecoin
- Solo
- Switch
- Removed Google Wallet
image

By looping through all `shop.enabled_payment_types` in the footer, we're suseptible to showing new payment types before an icon is added to Timber's icon set. I've added in a _whitelist_ to only hold the ones we have icons for.

#### Other new icons
- Instagram's new logo
- Updated Google+ logo (now named `google-plus`, instead of `google`)

image

@stevebosworth @Lisa-Villeneuve @carolineschnapp

### CODE REVIEW

**Comment by Lisa-Villeneuve** [comment]
Looks good to me on my test shop. The whitelist idea is great 👍

**Comment by suture** [comment]
Haven't Switch and Solo been killed off now, replaced by Maestro?

https://en.wikipedia.org/wiki/Solo_%28debit_card%29
https://en.wikipedia.org/wiki/Switch_%28debit_card%29

**Comment by cshold** [comment]
Yup, it looks like those are no longer active yet still show up as available methods in Shopify [source](https://help.shopify.com/themes/customization/store/add-credit-card-icons). I'll ask around about getting the legacy payment methods fully removed, then update the icon set again once they are.

**Comment by matcaissy** [comment]
@cshold Please see https://github.com/Shopify/shopify-themes/pull/3347#issuecomment-220394997

**Comment by cshold** [comment]
For those that couldn't see the private link above, it was about icon alignment — specifically with Instagram and Google+. I went through and updated every icon we have to be better aligned and sized.

image

**Pull request merged**
