### PR TITLE
Add Apple wallet button to gift card template

### PR DESCRIPTION
**Pull request by blboyle**
I made the updates for adding the Apple wallet button to the gift card template, to account for Apple's wallet, and showing the QR code all the time, instead of only on print.

@ohsabry can you check this out for me?

### CODE REVIEW

**Comment by ohsabry** [comment]
Thanks. Code looks fine, is there any way I can :tophat: ?

**Comment by blboyle** [comment]
This seems like it works, but we don't see the Apple wallet button for some reason. 

https://checkout.shopify.com/gift_cards/10007292/preview this should show you the example of the new gift card page in my test store.

**Comment by cshold** [comment]
:+1:

**Comment by ohsabry** [comment]
@blboyle Sorry, a few gotchas

One is that the beta flag name was changed from `passbook` to `apple_pass`. 

The other is that non alphanumeric characters other than spaces are currently not allowed for the pass title, and your shop name has an exclamation point. I'll fix that today. 

The last one is that you button won't download a pass if the shop is password protected. 

I was able to go into your shop, add the new beta flag, enable apple wallet, and get it to appear: 
https://checkout.shopify.com/gift_cards/10007292/cd7c26541fb53b0b64b4bc9ce11cc66c

**Pull request merged**
