### PR TITLE
[i18n] Tests for i18n validation

### PR DESCRIPTION
**Pull request by haeky**
We need tests for i18n keys in Timber. 

There will be a test for:
* Missing and unused keys in default locale that's present in .liquid 
* Missing and extra keys in default locale that are not in other locales
* HTML validity for _html keys

### CODE REVIEW

**Comment by haeky** [comment]
ping @cshold 

Should I add documentation?

**Comment by cshold** [comment]
Amazing. Yes, some documentation in the main readme would be great - maybe right under **Basic Structure**?

**Comment by haeky** [comment]
Is that clear enough in your opinion @cshold?

**Comment by cshold** [comment]
How about:

i18n CircleCI Testing
---------------------
CircleCI tests make sure there are no missing or extra i18n strings. HTML in locale files is also validated.

All PRs must pass the tests before being merged. Check the test status when you open a new PR on GitHub, or locally with the following.

-  `bundle install` to install all the dependecies
- `rspec spec` to run all the tests

**Comment by haeky** [comment]
Oh thanks a lot :)

**Comment by haeky** [comment]
I'm not sure if the tests are CircleCI related. If someone fork the project, he doesn't really need CircleCI?

**Comment by haeky** [comment]
i18n testing
---------------------
Tests make sure there are no missing or extra i18n strings or invalid html in your locale liquid files.

All PRs must pass the tests before being merged. Check the test status with the following.

-  `bundle install` to install all the dependecies
- `rspec spec` to run all the tests

**Comment by cshold** [comment]
The tests will automatically show as pass/fail on PRs though, right? It'd be nice if you didn't have to run them locally too.

**Comment by haeky** [comment]
I mean for this repository, but if you fork the project for your own theme, you'll have to setup CircleCI by yourself

**Comment by cshold** [comment]
Ah gotcha. I'd mention that doing the tests locally are optional because they'll happen on Timber PRs automagically. Other than that, :+1: glad to see this getting in here

**Pull request merged**
