### PR TITLE
changing line item ids to use keys

### PR DESCRIPTION
**Pull request by blboyle**
Changing ajax cart, customer order and cart templates to use key for line items instead of ids. 

cc/ @NathanPJF

### CODE REVIEW

**Comment by NathanPJF** [comment]
Small item : `{{key}}` isn't being passed on the cart page - [screenshot here](http://take.ms/PtjME).

Issue lies in how `qtySelectors()` is building data to the `id="JsQty"` script.

**Comment by blboyle** [comment]
@NathanPJF 

Can you take another look?

**Comment by NathanPJF** [comment]
🎩  - looks great, dude!

**Comment by gmalette** [comment]
Thanks for handling this!

**Pull request merged**
