### PR TITLE
Closes #540: Return schema.org-compliant pricing information.

### LINKED ISSUE #540: Incorrect schema.org pricing markup.
We get a lot of Shopify stores using Timber install our app, [JSON-LD for SEO](https://apps.shopify.com/json-ld-for-seo). One of the first things people do after installing the app is check their structured data report using Google's Structured Data testing tool.

There's an issue with the way Timber outputs product price information by default that we've seen repeatedly cause merchants concern - the `price` item property is being returned formatted, which Google doesn't expect.

I'll raise a PR with a fix.

### PR DESCRIPTION
**Pull request by gavinballard**

### CODE REVIEW

**Comment by cshold** [comment]
`money_without_currency` will still return the symbol, just not `CAD` or `USD`. The docs are a bit confusing - I'll get them updated.

Instead, you can use `content="{{ current_variant.price | divided_by: 100 }}"`

cc @carolineschnapp

**Comment by cshold** [comment]
I may have spoke too soon, hold tight.

**Comment by gavinballard** [comment]
I think you may have because `money_without_currency` seems to work find on the various themes I've used it with :).

**Comment by cshold** [comment]
The problem arises with changing the money format to `amount_with_comma_separator`. It causes an error in Google structured data testing tool:
image

Instead, we should use `content="{{ current_variant.price | divided_by: 100.00 }}`. This works with any money format and maintains the decimals.

Any objections @stevebosworth @m-ux @carolineschnapp?

**Comment by gavinballard** [comment]
Are there problems then if the currency doesn't use decimals? For example, here in Sweden all prices are just in SEK, without öre (cents). Does Shopify store 600 SEK as a price of `60000`, or `600`?

**Comment by cshold** [comment]
We're in the clear there.

If you have say $199.99 defined in CAD or USD then switch to SEK, it's rounded to SEK but still stored as the decimal value. Best explained below:
sek
That means `{{ product.price | divided_by: 100.00 }}` would still give you 199.99.

If you update the price to 200 even, then `{{ product.price | divided_by: 100.00 }}` would be 200.0, which is valid to Google:
image

To answer your initial question, yes, 200 SEK is 20000 with `{{ product.price }}`

**Comment by gavinballard** [comment]
Awesome, just updated the pull request.

**Comment by cshold** [comment]
Thanks!

**Pull request merged**
