### PR TITLE
Customer form style updates

### PR DESCRIPTION
**Pull request by cshold**
Minor style updates for customer area forms to ensure they're more unified in design.

cc/ @mpiotrowicz @stevebosworth

### CODE REVIEW

**Comment by mpiotrowicz** [comment]
code looks good, but are these design elements needed to display the forms?

**Comment by cshold** [comment]
To display them in line with the other base styles, yes. They were missed when changing the default form styles in an earlier PR. For example, the forgot password form:

Before:
screen shot 2015-03-19 at 1 24 05 pm

After:
screen shot 2015-03-19 at 1 24 48 pm

**Comment by cshold** [comment]
The above screenshots make more sense when you look at the login form too (which no moves the 'forgot password' link below the Sign in button):
screen shot 2015-03-19 at 1 25 51 pm

**Comment by cshold** [comment]
@mpiotrowicz good to go?

**Pull request merged**
